/* =========================================================
   OFFICIAL ASSETS （自動生成 — 直接編集しないこと）
   生成日時: 2026-08-26T12:24:16.218Z
   生成コマンド: node tools/fetch-assets.mjs
   出典: Riot Games / valorant-api.com
   ========================================================= */
(function (global) {
  'use strict';
  const AGENTS = {
  "jett": "assets/img/agents/jett.png",
  "phoenix": "assets/img/agents/phoenix.png",
  "raze": "assets/img/agents/raze.png",
  "reyna": "assets/img/agents/reyna.png",
  "yoru": "assets/img/agents/yoru.png",
  "neon": "assets/img/agents/neon.png",
  "iso": "assets/img/agents/iso.png",
  "waylay": "assets/img/agents/waylay.png",
  "sova": "assets/img/agents/sova.png",
  "breach": "assets/img/agents/breach.png",
  "skye": "assets/img/agents/skye.png",
  "kayo": "assets/img/agents/kayo.png",
  "fade": "assets/img/agents/fade.png",
  "gekko": "assets/img/agents/gekko.png",
  "tejo": "assets/img/agents/tejo.png",
  "brimstone": "assets/img/agents/brimstone.png",
  "omen": "assets/img/agents/omen.png",
  "viper": "assets/img/agents/viper.png",
  "astra": "assets/img/agents/astra.png",
  "harbor": "assets/img/agents/harbor.png",
  "clove": "assets/img/agents/clove.png",
  "miks": "assets/img/agents/miks.png",
  "killjoy": "assets/img/agents/killjoy.png",
  "cypher": "assets/img/agents/cypher.png",
  "sage": "assets/img/agents/sage.png",
  "chamber": "assets/img/agents/chamber.png",
  "deadlock": "assets/img/agents/deadlock.png",
  "vyse": "assets/img/agents/vyse.png",
  "veto": "assets/img/agents/veto.png"
};
  const MAPS = {
  "ascent": "assets/img/maps/ascent.png",
  "bind": "assets/img/maps/bind.png",
  "haven": "assets/img/maps/haven.png",
  "split": "assets/img/maps/split.png",
  "icebox": "assets/img/maps/icebox.png",
  "breeze": "assets/img/maps/breeze.png",
  "fracture": "assets/img/maps/fracture.png",
  "pearl": "assets/img/maps/pearl.png",
  "lotus": "assets/img/maps/lotus.png",
  "sunset": "assets/img/maps/sunset.png",
  "abyss": "assets/img/maps/abyss.png",
  "corrode": "assets/img/maps/corrode.png",
  "summit": "assets/img/maps/summit.png"
};
  const ABILITY_ICONS = {
  "jett:Q": "assets/img/abilities/jett_Q.png",
  "jett:E": "assets/img/abilities/jett_E.png",
  "jett:C": "assets/img/abilities/jett_C.png",
  "jett:X": "assets/img/abilities/jett_X.png",
  "phoenix:C": "assets/img/abilities/phoenix_C.png",
  "phoenix:Q": "assets/img/abilities/phoenix_Q.png",
  "phoenix:E": "assets/img/abilities/phoenix_E.png",
  "phoenix:X": "assets/img/abilities/phoenix_X.png",
  "raze:Q": "assets/img/abilities/raze_Q.png",
  "raze:E": "assets/img/abilities/raze_E.png",
  "raze:C": "assets/img/abilities/raze_C.png",
  "raze:X": "assets/img/abilities/raze_X.png",
  "reyna:Q": "assets/img/abilities/reyna_Q.png",
  "reyna:E": "assets/img/abilities/reyna_E.png",
  "reyna:C": "assets/img/abilities/reyna_C.png",
  "reyna:X": "assets/img/abilities/reyna_X.png",
  "yoru:C": "assets/img/abilities/yoru_C.png",
  "yoru:Q": "assets/img/abilities/yoru_Q.png",
  "yoru:E": "assets/img/abilities/yoru_E.png",
  "yoru:X": "assets/img/abilities/yoru_X.png",
  "neon:E": "assets/img/abilities/neon_E.png",
  "neon:Q": "assets/img/abilities/neon_Q.png",
  "neon:C": "assets/img/abilities/neon_C.png",
  "neon:X": "assets/img/abilities/neon_X.png",
  "iso:Q": "assets/img/abilities/iso_Q.png",
  "iso:X": "assets/img/abilities/iso_X.png",
  "iso:E": "assets/img/abilities/iso_E.png",
  "iso:C": "assets/img/abilities/iso_C.png",
  "waylay:E": "assets/img/abilities/waylay_E.png",
  "waylay:C": "assets/img/abilities/waylay_C.png",
  "waylay:Q": "assets/img/abilities/waylay_Q.png",
  "waylay:X": "assets/img/abilities/waylay_X.png",
  "sova:Q": "assets/img/abilities/sova_Q.png",
  "sova:E": "assets/img/abilities/sova_E.png",
  "sova:C": "assets/img/abilities/sova_C.png",
  "sova:X": "assets/img/abilities/sova_X.png",
  "breach:Q": "assets/img/abilities/breach_Q.png",
  "breach:E": "assets/img/abilities/breach_E.png",
  "breach:C": "assets/img/abilities/breach_C.png",
  "breach:X": "assets/img/abilities/breach_X.png",
  "skye:Q": "assets/img/abilities/skye_Q.png",
  "skye:E": "assets/img/abilities/skye_E.png",
  "skye:C": "assets/img/abilities/skye_C.png",
  "skye:X": "assets/img/abilities/skye_X.png",
  "kayo:C": "assets/img/abilities/kayo_C.png",
  "kayo:Q": "assets/img/abilities/kayo_Q.png",
  "kayo:E": "assets/img/abilities/kayo_E.png",
  "kayo:X": "assets/img/abilities/kayo_X.png",
  "fade:Q": "assets/img/abilities/fade_Q.png",
  "fade:E": "assets/img/abilities/fade_E.png",
  "fade:C": "assets/img/abilities/fade_C.png",
  "fade:X": "assets/img/abilities/fade_X.png",
  "gekko:Q": "assets/img/abilities/gekko_Q.png",
  "gekko:E": "assets/img/abilities/gekko_E.png",
  "gekko:C": "assets/img/abilities/gekko_C.png",
  "gekko:X": "assets/img/abilities/gekko_X.png",
  "tejo:E": "assets/img/abilities/tejo_E.png",
  "tejo:Q": "assets/img/abilities/tejo_Q.png",
  "tejo:X": "assets/img/abilities/tejo_X.png",
  "tejo:C": "assets/img/abilities/tejo_C.png",
  "brimstone:C": "assets/img/abilities/brimstone_C.png",
  "brimstone:Q": "assets/img/abilities/brimstone_Q.png",
  "brimstone:E": "assets/img/abilities/brimstone_E.png",
  "brimstone:X": "assets/img/abilities/brimstone_X.png",
  "omen:Q": "assets/img/abilities/omen_Q.png",
  "omen:E": "assets/img/abilities/omen_E.png",
  "omen:C": "assets/img/abilities/omen_C.png",
  "omen:X": "assets/img/abilities/omen_X.png",
  "viper:Q": "assets/img/abilities/viper_Q.png",
  "viper:E": "assets/img/abilities/viper_E.png",
  "viper:C": "assets/img/abilities/viper_C.png",
  "viper:X": "assets/img/abilities/viper_X.png",
  "astra:Q": "assets/img/abilities/astra_Q.png",
  "astra:E": "assets/img/abilities/astra_E.png",
  "astra:C": "assets/img/abilities/astra_C.png",
  "astra:X": "assets/img/abilities/astra_X.png",
  "harbor:Q": "assets/img/abilities/harbor_Q.png",
  "harbor:C": "assets/img/abilities/harbor_C.png",
  "harbor:E": "assets/img/abilities/harbor_E.png",
  "harbor:X": "assets/img/abilities/harbor_X.png",
  "clove:C": "assets/img/abilities/clove_C.png",
  "clove:E": "assets/img/abilities/clove_E.png",
  "clove:X": "assets/img/abilities/clove_X.png",
  "clove:Q": "assets/img/abilities/clove_Q.png",
  "miks:C": "assets/img/abilities/miks_C.png",
  "miks:E": "assets/img/abilities/miks_E.png",
  "miks:Q": "assets/img/abilities/miks_Q.png",
  "miks:X": "assets/img/abilities/miks_X.png",
  "killjoy:C": "assets/img/abilities/killjoy_C.png",
  "killjoy:Q": "assets/img/abilities/killjoy_Q.png",
  "killjoy:E": "assets/img/abilities/killjoy_E.png",
  "killjoy:X": "assets/img/abilities/killjoy_X.png",
  "cypher:Q": "assets/img/abilities/cypher_Q.png",
  "cypher:E": "assets/img/abilities/cypher_E.png",
  "cypher:C": "assets/img/abilities/cypher_C.png",
  "cypher:X": "assets/img/abilities/cypher_X.png",
  "sage:Q": "assets/img/abilities/sage_Q.png",
  "sage:E": "assets/img/abilities/sage_E.png",
  "sage:C": "assets/img/abilities/sage_C.png",
  "sage:X": "assets/img/abilities/sage_X.png",
  "chamber:E": "assets/img/abilities/chamber_E.png",
  "chamber:C": "assets/img/abilities/chamber_C.png",
  "chamber:Q": "assets/img/abilities/chamber_Q.png",
  "chamber:X": "assets/img/abilities/chamber_X.png",
  "deadlock:Q": "assets/img/abilities/deadlock_Q.png",
  "deadlock:C": "assets/img/abilities/deadlock_C.png",
  "deadlock:E": "assets/img/abilities/deadlock_E.png",
  "deadlock:X": "assets/img/abilities/deadlock_X.png",
  "vyse:Q": "assets/img/abilities/vyse_Q.png",
  "vyse:E": "assets/img/abilities/vyse_E.png",
  "vyse:C": "assets/img/abilities/vyse_C.png",
  "vyse:X": "assets/img/abilities/vyse_X.png",
  "veto:E": "assets/img/abilities/veto_E.png",
  "veto:C": "assets/img/abilities/veto_C.png",
  "veto:X": "assets/img/abilities/veto_X.png",
  "veto:Q": "assets/img/abilities/veto_Q.png"
};
  const ABILITY_NAMES = {
  "ja": {
    "jett:Q": "アップドラフト",
    "jett:E": "テイルウィンド",
    "jett:C": "クラウドバースト",
    "jett:X": "ブレードストーム",
    "phoenix:C": "ブレイズ",
    "phoenix:Q": "ホットハンド",
    "phoenix:E": "カーブボール",
    "phoenix:X": "ラン・イット・バック",
    "raze:Q": "ブラストパック",
    "raze:E": "ペイント弾",
    "raze:C": "ブームボット",
    "raze:X": "ショーストッパー",
    "reyna:Q": "デバウアー",
    "reyna:E": "ディスミス",
    "reyna:C": "リーア",
    "reyna:X": "エンプレス",
    "yoru:C": "フェイクアウト",
    "yoru:Q": "ブラインドサイド",
    "yoru:E": "ゲートクラッシュ",
    "yoru:X": "ディメンショナル\nドリフト",
    "neon:E": "ハイギア",
    "neon:Q": "リレーボルト",
    "neon:C": "ファストレーン",
    "neon:X": "オーバードライブ",
    "iso:Q": "アンダーカット",
    "iso:X": "キルコントラクト",
    "iso:E": "ダブルタップ",
    "iso:C": "コンティンジェンシー",
    "waylay:E": "リフラクト",
    "waylay:C": "サチュレート",
    "waylay:Q": "ライトスピード",
    "waylay:X": "コンバージェントパス",
    "sova:Q": "ショックボルト",
    "sova:E": "リコンボルト",
    "sova:C": "オウルドローン",
    "sova:X": "ハンターズフューリー",
    "breach:Q": "フラッシュポイント",
    "breach:E": "フォールトライン",
    "breach:C": "アフターショック",
    "breach:X": "ローリングサンダー",
    "skye:Q": "トレイルブレイザー",
    "skye:E": "ガイディングライト",
    "skye:C": "リグロウス",
    "skye:X": "シーカー",
    "kayo:C": "フラグ/メント",
    "kayo:Q": "フラッシュ/ドライブ",
    "kayo:E": "ゼロ/ポイント",
    "kayo:X": "ヌル/コマンド",
    "fade:Q": "シーズ",
    "fade:E": "ホウント",
    "fade:C": "プラウラー",
    "fade:X": "ナイトフォール",
    "gekko:Q": "ウィングマン",
    "gekko:E": "ディジー",
    "gekko:C": "モッシュピット",
    "gekko:X": "スラッシュ",
    "tejo:E": "誘導サルヴォ",
    "tejo:Q": "スペシャルデリバリー",
    "tejo:X": "アルマゲドン",
    "tejo:C": "ステルスドローン",
    "brimstone:C": "スティムビーコン",
    "brimstone:Q": "インセンディアリー",
    "brimstone:E": "スカイスモーク",
    "brimstone:X": "オービタルストライク",
    "omen:Q": "パラノイア",
    "omen:E": "ダークカヴァー",
    "omen:C": "シュラウドステップ",
    "omen:X": "フロム・ザ・シャドウズ",
    "viper:Q": "ポイズンクラウド",
    "viper:E": "トキシックスクリーン",
    "viper:C": "スネークバイト",
    "viper:X": "ヴァイパーズピット",
    "astra:Q": "ノヴァパルス",
    "astra:E": "ネビュラ / ディシペイト",
    "astra:C": "グラビティウェル",
    "astra:X": "アストラルフォーム /\nコズミックディバイド",
    "harbor:Q": "ハイタイド",
    "harbor:C": "ストームサージ",
    "harbor:E": "コーヴ",
    "harbor:X": "レコニング",
    "clove:C": "ピック・ミー・アップ",
    "clove:E": "ルース",
    "clove:X": "ノット・デッド・イェット",
    "clove:Q": "メドル",
    "miks:C": "M-パルス",
    "miks:E": "ウェーブフォーム",
    "miks:Q": "ハーモナイズ",
    "miks:X": "ベースクエイク",
    "killjoy:C": "ナノスワーム",
    "killjoy:Q": "アラームボット",
    "killjoy:E": "タレット",
    "killjoy:X": "ロックダウン",
    "cypher:Q": "サイバーケージ",
    "cypher:E": "スパイカメラ",
    "cypher:C": "トラップワイヤー",
    "cypher:X": "ニューラルセフト",
    "sage:Q": "スロウオーブ",
    "sage:E": "ヒーリングオーブ",
    "sage:C": "バリアオーブ",
    "sage:X": "リザレクション",
    "chamber:E": "ランデヴー",
    "chamber:C": "トレードマーク",
    "chamber:Q": "ヘッドハンター",
    "chamber:X": "ツール・ド・フォース",
    "deadlock:Q": "ソニックセンサー",
    "deadlock:C": "バリアメッシュ",
    "deadlock:E": "グラヴィネット",
    "deadlock:X": "アナイアレーション",
    "vyse:Q": "シアー",
    "vyse:E": "アークローズ",
    "vyse:C": "レーザーヴァイン",
    "vyse:X": "スチールガーデン",
    "veto:E": "インタセプター",
    "veto:C": "クロスカット",
    "veto:X": "エヴォリューション",
    "veto:Q": "チョークホールド"
  },
  "en": {
    "jett:Q": "Updraft",
    "jett:E": "Tailwind",
    "jett:C": "Cloudburst",
    "jett:X": "Blade Storm",
    "phoenix:C": "Blaze",
    "phoenix:Q": "Hot Hands",
    "phoenix:E": "Curveball",
    "phoenix:X": "Run it Back",
    "raze:Q": "Blast Pack",
    "raze:E": "Paint Shells",
    "raze:C": "Boom Bot",
    "raze:X": "Showstopper",
    "reyna:Q": "Devour",
    "reyna:E": "Dismiss",
    "reyna:C": "Leer",
    "reyna:X": "Empress",
    "yoru:C": "FAKEOUT",
    "yoru:Q": "BLINDSIDE",
    "yoru:E": "GATECRASH",
    "yoru:X": "DIMENSIONAL DRIFT",
    "neon:E": "High Gear",
    "neon:Q": "Relay Bolt",
    "neon:C": "Fast Lane",
    "neon:X": "Overdrive",
    "iso:Q": "Undercut",
    "iso:X": "Kill Contract",
    "iso:E": "Double Tap",
    "iso:C": "Contingency",
    "waylay:E": "Refract",
    "waylay:C": "Saturate",
    "waylay:Q": "Lightspeed",
    "waylay:X": "Convergent Paths",
    "sova:Q": "Shock Bolt",
    "sova:E": "Recon Bolt",
    "sova:C": "Owl Drone",
    "sova:X": "Hunter's Fury",
    "breach:Q": "Flashpoint",
    "breach:E": "Fault Line",
    "breach:C": "Aftershock",
    "breach:X": "Rolling Thunder",
    "skye:Q": "Trailblazer",
    "skye:E": "Guiding Light",
    "skye:C": "Regrowth",
    "skye:X": "Seekers",
    "kayo:C": "FRAG/ment",
    "kayo:Q": "FLASH/drive",
    "kayo:E": "ZERO/point",
    "kayo:X": "NULL/cmd",
    "fade:Q": "Seize",
    "fade:E": "Haunt",
    "fade:C": "Prowler",
    "fade:X": "Nightfall",
    "gekko:Q": "Wingman",
    "gekko:E": "Dizzy",
    "gekko:C": "Mosh Pit",
    "gekko:X": "Thrash",
    "tejo:E": "Guided Salvo",
    "tejo:Q": "Special Delivery",
    "tejo:X": "Armageddon",
    "tejo:C": "Stealth Drone",
    "brimstone:C": "Stim Beacon",
    "brimstone:Q": "Incendiary",
    "brimstone:E": "Sky Smoke",
    "brimstone:X": "Orbital Strike",
    "omen:Q": "Paranoia",
    "omen:E": "Dark Cover",
    "omen:C": "Shrouded Step",
    "omen:X": "From the Shadows",
    "viper:Q": "Poison Cloud",
    "viper:E": "Toxic Screen",
    "viper:C": "Snake Bite",
    "viper:X": "Viper's Pit",
    "astra:Q": "Nova Pulse",
    "astra:E": "Nebula  / Dissipate",
    "astra:C": "Gravity Well",
    "astra:X": "Astral Form / Cosmic Divide",
    "harbor:Q": "High Tide",
    "harbor:C": "Storm Surge",
    "harbor:E": "Cove",
    "harbor:X": "Reckoning",
    "clove:C": "Pick-me-up",
    "clove:E": "Ruse",
    "clove:X": "Not Dead Yet",
    "clove:Q": "Meddle",
    "miks:C": "M-pulse",
    "miks:E": "Waveform",
    "miks:Q": "Harmonize",
    "miks:X": "Bassquake",
    "killjoy:C": "Nanoswarm",
    "killjoy:Q": "ALARMBOT",
    "killjoy:E": "TURRET",
    "killjoy:X": "Lockdown",
    "cypher:Q": "Cyber Cage",
    "cypher:E": "Spycam",
    "cypher:C": "Trapwire",
    "cypher:X": "Neural Theft",
    "sage:Q": "Slow Orb",
    "sage:E": "Healing Orb",
    "sage:C": "Barrier Orb",
    "sage:X": "Resurrection",
    "chamber:E": "Rendezvous",
    "chamber:C": "Trademark",
    "chamber:Q": "Headhunter",
    "chamber:X": "Tour De Force",
    "deadlock:Q": "Sonic Sensor",
    "deadlock:C": "Barrier Mesh",
    "deadlock:E": "GravNet",
    "deadlock:X": "Annihilation",
    "vyse:Q": "Shear",
    "vyse:E": "Arc Rose",
    "vyse:C": "Razorvine",
    "vyse:X": "Steel Garden",
    "veto:E": "Interceptor",
    "veto:C": "Crosscut",
    "veto:X": "Evolution",
    "veto:Q": "Chokehold"
  },
  "ko": {
    "jett:Q": "상승 기류",
    "jett:E": "순풍",
    "jett:C": "연막 폭발",
    "jett:X": "칼날 폭풍",
    "phoenix:C": "불길",
    "phoenix:Q": "뜨거운 손",
    "phoenix:E": "커브볼",
    "phoenix:X": "역습",
    "raze:Q": "폭발 팩",
    "raze:E": "페인트탄",
    "raze:C": "폭발 봇",
    "raze:X": "대미 장식",
    "reyna:Q": "포식",
    "reyna:E": "무시",
    "reyna:C": "눈총",
    "reyna:X": "여제",
    "yoru:C": "기만",
    "yoru:Q": "기습",
    "yoru:E": "관문 충돌",
    "yoru:X": "차원 표류",
    "neon:E": "고속 기어",
    "neon:Q": "릴레이 볼트",
    "neon:C": "추월 차선",
    "neon:X": "오버드라이브",
    "iso:Q": "약화",
    "iso:X": "청부 계약",
    "iso:E": "구슬 보호막",
    "iso:C": "대비책",
    "waylay:E": "굴절",
    "waylay:C": "포화",
    "waylay:Q": "광속",
    "waylay:X": "초점 교차",
    "sova:Q": "충격 화살",
    "sova:E": "정찰용 화살",
    "sova:C": "올빼미 드론",
    "sova:X": "사냥꾼의 분노",
    "breach:Q": "섬광 폭발",
    "breach:E": "균열",
    "breach:C": "여진",
    "breach:X": "지진 강타",
    "skye:Q": "정찰자",
    "skye:E": "인도하는 빛",
    "skye:C": "재생",
    "skye:X": "추적자",
    "kayo:C": "파편/탄",
    "kayo:Q": "플래시/드라이브",
    "kayo:E": "제로/포인트",
    "kayo:X": "무력화/명령",
    "fade:Q": "포박",
    "fade:E": "귀체",
    "fade:C": "추적귀",
    "fade:X": "황혼",
    "gekko:Q": "지원봇",
    "gekko:E": "기절봇",
    "gekko:C": "폭파봇 지옥",
    "gekko:X": "요동봇",
    "tejo:E": "유도 일제 사격",
    "tejo:Q": "특별 배송",
    "tejo:X": "아마겟돈",
    "tejo:C": "잠입 드론",
    "brimstone:C": "자극제 신호기",
    "brimstone:Q": "소이탄",
    "brimstone:E": "공중 연막",
    "brimstone:X": "궤도 일격",
    "omen:Q": "피해망상",
    "omen:E": "어둠의 장막",
    "omen:C": "어둠의 발자국",
    "omen:X": "그림자 습격",
    "viper:Q": "독성 연기",
    "viper:E": "독성 장막",
    "viper:C": "뱀 이빨",
    "viper:X": "독사의 구덩이",
    "astra:Q": "신성 파동",
    "astra:E": "성운 / 소멸",
    "astra:C": "중력의 샘",
    "astra:X": "천상계 형상 / 우주 장벽",
    "harbor:Q": "만조",
    "harbor:C": "폭풍 쇄도",
    "harbor:E": "해만",
    "harbor:X": "심판",
    "clove:C": "활력 회복",
    "clove:E": "계략",
    "clove:X": "아직 안 죽었어",
    "clove:Q": "간섭",
    "miks:C": "M-파동",
    "miks:E": "웨이브폼",
    "miks:Q": "화음",
    "miks:X": "요동치는 베이스",
    "killjoy:C": "나노스웜",
    "killjoy:Q": "알람봇",
    "killjoy:E": "포탑",
    "killjoy:X": "봉쇄",
    "cypher:Q": "사이버 감옥",
    "cypher:E": "스파이캠",
    "cypher:C": "함정",
    "cypher:X": "신경 절도",
    "sage:Q": "둔화 구슬",
    "sage:E": "회복 구슬",
    "sage:C": "장벽 구슬",
    "sage:X": "부활",
    "chamber:E": "랑데부",
    "chamber:C": "트레이드마크",
    "chamber:Q": "헤드헌터",
    "chamber:X": "역작",
    "deadlock:Q": "음향 센서",
    "deadlock:C": "장벽망",
    "deadlock:E": "중력그물",
    "deadlock:X": "소멸",
    "vyse:Q": "가지치기",
    "vyse:E": "아크 장미",
    "vyse:C": "면도날 덩굴",
    "vyse:X": "강철 정원",
    "veto:E": "요격기",
    "veto:C": "지름길",
    "veto:X": "진화",
    "veto:Q": "목조르기"
  }
};
  const SPIKE = "assets/img/spike.png";

  /* board.js はこの後に読み込まれるので、素のグローバルに置いておく */
  global.VCT_OFFICIAL_SPIKE = SPIKE;
  if (global.VCT_PORTRAITS) Object.assign(global.VCT_PORTRAITS.OFFICIAL, AGENTS);
  if (global.VCT_MAPS) Object.assign(global.VCT_MAPS.MINIMAP, MAPS);
  if (global.VCT_ABILITIES) {
    Object.assign(global.VCT_ABILITIES.OFFICIAL_ICONS, ABILITY_ICONS);
    Object.assign(global.VCT_ABILITIES.OFFICIAL_NAMES, ABILITY_NAMES);
  }
})(window);
